### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by medwatt** [Psykar/i3-backandforth-externalmonitor#1]
You could at least explain how to use it.

**Comment by Psykar** [comment]
Fair - it's pretty basic (and I don't currently use it, so YMMV) - updated the Readme.

**Comment by medwatt** [comment]
The first thing I did since there was no example on how to use this script was to run it and then try to switch between workspaces. It didn't notice any difference. That's why I opened an issue.

**Comment by Psykar** [comment]
If you're up for hacking things, you can change the logging level to debug in the python script and check the output.

logging.basicConfig(level=logging.DEBUG)

As mentioned I'm not currently using this, so it's more about publishing it in case other people find it useful to build on.

**Comment by medwatt** [comment]
Out of curiosity, what are using?

**Comment by Psykar** [comment]
Currently on `sway` (and to be honest I'm still occasionally bugged by the default behavior) but haven't had the inclination to port this to sway yet.

**Comment by medwatt** [comment]
The default behaviour makes no sense. Why would I want to toggle to the workspace on the monitor that I just left? I was hoping someone has already a script for that since I don't have the time to go through the i3ipc module yet.

As far as I know, isn't sway just i3 but for wayland? I have tried using wayland a couple of times, but switched back to xorg due to some weird issues.
